package.json
yarn.lock

Runs prettier on staged files (and fails if changes are needed), and
runs lint

chore: Add prepush sanity check

---

src/components/header/nav/nav.css.js

- Switch underline to be white to match link color (@alex LMK if this
was intentional)
- Change side padding to margins to avoid underline being too long

fix(Header): Fix link styles

---

.storybook/addons.js
.storybook/config.js
.storybook/decorators/StyleDecorator.js
.storybook/webpack.config.js
package.json
src/components/shared/button/button.js
src/components/shared/button/button.stories.js
yarn.lock

- Allow absolute paths
- Render global styles
- Load typefaces

fix(Storybook): Fix config

---

package.json
src/lambda/slackSubmit.js
yarn.lock

Turns out google only takes `x-www-form-encoded`, go figure.

fix(recaptcha): Fix POST params

---

content/pages/index.yaml
readme.md
src/components/shared/text/text.css.js
src/pages/index.js

Addresses (but doesn't finish) #52.

feat(Home): Add copy

---

src/components/shared/inviteform/inviteform.js
src/components/shared/resourcelist/resourcelist.js
src/pages/index.js

When clicked, smooth scrolls to the invite input field and focuses it.

feat: homepage slack button behavior

---

src/components/header/mobilenav/mobilenav.js

Animates exit when closing with corner X

fix: fix mobile nav close animation

---

src/components/header/mobilenav/mobilenav.css.js

Fix small scroll issues on mobile devices

fix: better positioning for mobile nav

---

src/components/shared/eventcard/eventcard.stories.js

fix: 🐛 update type knob in EventCard story

---

scripts/lighthouse.js
src/components/layout/layout.css.js

This also affects very large screens.

fix: fix max-width breaking magnification change

---

src/components/shared/animatedtitle/animatedtitle.js

They might wrap in weird ways.

refactor: filter out long phrases on mobile for typewriter

---

src/components/shared/animatedtitle/animatedtitle.css.js
src/components/shared/animatedtitle/animatedtitle.js

- Hide cursor character until typing animation starts
- Adjust word wrap on tablet (md) vs. phone (sm)

refactor: improve typewriter on tablets

---

src/components/shared/animatedtitle/animatedtitle.js

As Steve commented, looks weird for R.

fix: remove smart backspace from typewriter

---

src/components/shared/card/card.css.js

refactor(Card): Make drop shadow look a bit better

---

site-config.js

fix: remove trailing slash from OG site URLs

---

src/components/layout/layout.css.js
src/helpers/wrapPageElement.js

This hides the font-face swap that happens due to the fonts loading in.
Also looks kinda nice!

feat: add app load animation

---

src/components/header/header.css.js
src/components/shared/button/button.css.js
src/components/shared/inviteform/inviteform.css.js
src/components/shared/inviteform/inviteform.js
src/constants/theme/shadows.js

This continues the design theme of adding subtle shadows to CTAs, to
make them stand out from the page further.

feat: add shadow to buttons

---

src/components/homepage/index.js

Prevents buttons getting cut off.

refactor: add more bottom padding to hero on mobile

---

content/pages/index.yaml
src/images/mailto-icon.svg
src/pages/about.js
src/pages/resources.js

Quick and dirty solution for V1. Can add a form in a modal in the
future.
Fixes #50.

feat(About): Mailto contact link

---

content/pages/index.yaml

chore: update index copy

---

src/components/shared/day/day.css.js
src/components/shared/day/day.js
src/components/shared/eventlist/eventlist.js

Also adds a new label for events happening now in the events list.

fix: fix events happening now being filtered out
